### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by reinhardt**

### CODE REVIEW

**Comment by reinhardt** [comment]
`sphinxcontrib-zopeext` and `sphinxcontrib-spelling` are installed via buildout but not registered in `conf.py` and therefore not used.

`repoze.sphinx.autointerface` seems to be working fine.

@pilz, should I 

* throw out the inactive plugins?
* activate the inactive plugins?
* leave the plugins as they are?

**Comment by pilz** [comment]
Remove what is not used or needed.

**Comment by reinhardt** [comment]
Define “needed”?

**Comment by pilz** [comment]
--needed-- used

**Pull request merged**
